export const DUMMY_USERS = [
    {
      id: 1,
      name: 'Qamardeen Abdulmalik',
      username: 'Alucard',
      email: 'johndoe@gmail.com',
      mobileNumber: '+234123456789',
      password: '****',
      gender: 'Male',
      referralCode: null,
      category: 'Team',
      kycStatus: 'successful',
      tier: 'Gold',
      dateJoined: 'Nov 7, 2024',
      lastPasswordReset: 'Nov 1, 2024',
      accountActivities: []
    },
    {
      id: 2,
      name: 'Sophia Johnson',
      username: 'Sophie21',
      email: 'sophia.johnson@example.com',
      mobileNumber: '+123456789012',
      password: '****',
      gender: 'Female',
      referralCode: 'REF123',
      category: 'Admin',
      kycStatus: 'approved',
      tier: 'Platinum',
      dateJoined: 'Oct 15, 2024',
      lastPasswordReset: 'Oct 10, 2024',
      accountActivities: []
    },
    {
      id: 3,
      name: 'James Smith',
      username: 'JSmith98',
      email: 'james.smith@example.com',
      mobileNumber: '+19876543210',
      password: '****',
      gender: 'Male',
      referralCode: null,
      category: 'Team',
      kycStatus: 'pending',
      tier: 'Silver',
      dateJoined: 'Sep 20, 2024',
      lastPasswordReset: 'Sep 10, 2024',
      accountActivities: []
    },
    {
      id: 4,
      name: 'Emily Davis',
      username: 'EmD123',
      email: 'emily.davis@example.com',
      mobileNumber: '+111223344556',
      password: '****',
      gender: 'Female',
      referralCode: 'REF456',
      category: 'Customer',
      kycStatus: 'approved',
      tier: 'Gold',
      dateJoined: 'Aug 22, 2024',
      lastPasswordReset: 'Aug 5, 2024',
      accountActivities: []
    },
    {
      id: 5,
      name: 'Michael Brown',
      username: 'MikeBrown',
      email: 'michael.brown@example.com',
      mobileNumber: '+12133445566',
      password: '****',
      gender: 'Male',
      referralCode: 'REF789',
      category: 'Admin',
      kycStatus: 'approved',
      tier: 'Platinum',
      dateJoined: 'Jul 18, 2024',
      lastPasswordReset: 'Jul 12, 2024',
      accountActivities: []
    },
    {
      id: 6,
      name: 'Olivia Wilson',
      username: 'OliviaW',
      email: 'olivia.wilson@example.com',
      mobileNumber: '+13098765432',
      password: '****',
      gender: 'Female',
      referralCode: null,
      category: 'Customer',
      kycStatus: 'successful',
      tier: 'Silver',
      dateJoined: 'Jun 5, 2024',
      lastPasswordReset: 'May 25, 2024',
      accountActivities: []
    },
    {
      id: 7,
      name: 'Daniel Garcia',
      username: 'DanGarcia',
      email: 'daniel.garcia@example.com',
      mobileNumber: '+14121234567',
      password: '****',
      gender: 'Male',
      referralCode: 'REF101',
      category: 'Team',
      kycStatus: 'approved',
      tier: 'Gold',
      dateJoined: 'May 10, 2024',
      lastPasswordReset: 'Apr 30, 2024',
      accountActivities: []
    },
    {
      id: 8,
      name: 'Ava Martinez',
      username: 'AvaM_22',
      email: 'ava.martinez@example.com',
      mobileNumber: '+15234567890',
      password: '****',
      gender: 'Female',
      referralCode: 'REF112',
      category: 'Customer',
      kycStatus: 'declined',
      tier: 'Bronze',
      dateJoined: 'Apr 12, 2024',
      lastPasswordReset: 'Mar 28, 2024',
      accountActivities: []
    },
    {
      id: 9,
      name: 'Ethan Taylor',
      username: 'EthanT',
      email: 'ethan.taylor@example.com',
      mobileNumber: '+16123456789',
      password: '****',
      gender: 'Male',
      referralCode: null,
      category: 'Team',
      kycStatus: 'approved',
      tier: 'Silver',
      dateJoined: 'Mar 25, 2024',
      lastPasswordReset: 'Mar 15, 2024',
      accountActivities: []
    },
    {
      id: 10,
      name: 'Isabella Moore',
      username: 'IsabellaM',
      email: 'isabella.moore@example.com',
      mobileNumber: '+17098765432',
      password: '****',
      gender: 'Female',
      referralCode: 'REF131',
      category: 'Admin',
      kycStatus: 'pending',
      tier: 'Platinum',
      dateJoined: 'Feb 18, 2024',
      lastPasswordReset: 'Feb 10, 2024',
      accountActivities: []
    }
  ]
  